### ISSUE TITLE
Tabelle fehlt der rex_-Präfix

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/yrewrite_domain_settings#14]
Dadurch wird sie nicht in den Backup-Cronjob aufgenommen

**Comment by skerbis** [comment]
der rex_ prefix ist nicht fix. Kann man das anders lösen?

**Comment by AWqxKAWERbXo** [comment]
nicht, wenn man Tabellen über den YForm Table Manager importieren möchte. Dann wäre ein Issue dort nötig.

**Comment by skerbis** [comment]
Das Problem liegt dann eher beim Backup addon

**Comment by skerbis** [comment]
Alternativ müsste das Tableset erst bei install generiert werden - d.h. Es müsste erst per php erzeugt werden
