### ISSUE TITLE
Plugin: Legal - Für Impressum, Kontakt und Co.

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/yrewrite_domain_settings#16]
Stellt opt. ein Plugin mit passender Tabelle mit Feldern rund um das Thema Impressum und Kontakt zur Verfügung. Einschl. Demo-Modul

**Comment by skerbis** [comment]
Hmm, das kann man doch schon selbst mit dem yform Feldern anlegen

**Comment by AWqxKAWERbXo** [comment]
Ich möchte das gerne etwas strukturieren und optional machen. Sonst ist der Nutzen von dem Addon für mich dahin, wenn da nicht sinnvolle presets mitkommen, sondern nur eine (leere) Tabelle installiert wird.

**Comment by skerbis** [comment]
Schade. Bin raus

**Comment by AWqxKAWERbXo** [comment]
Lass dich doch erstmal positiv überraschen!

**Comment by skerbis** [comment]
Die Sache ist, dass es solche AddOns schon gibt. Diese könnten aus meiner Sicht ergänzend erweitert werden. Dieses hier kann so schön schlank und flexibel bleiben.

**Comment by AWqxKAWERbXo** [comment]
Dem Wunsch komme ich doch nach entsprechend mit einem optionalen Plugin.

**Comment by AWqxKAWERbXo** [comment]
Und wo gibt's das Feature schon?

**Comment by skerbis** [comment]
Hattest du nicht schon so ein Addon? Auch inkl. Datenschutz und so?

**Comment by skerbis** [comment]
Global Settings ist auch noch ein Kandidat

**Comment by AWqxKAWERbXo** [comment]
Global Settings kann das nicht an der Domain
