### ISSUE TITLE
Plugin: Corporate Design Settings

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/yrewrite_domain_settings#17]
Stellt opt. ein Plugin mit passender Tabelle mit Feldern rund um das Thema Logo, Theming und Corporate Identity zur Verfügung. Einschl. Demo-Template.

**Comment by skerbis** [comment]
Hier könnte ich mir eher nötige Werkzeuge vorstellen, denn fertige Settings. Colorpicker, sass / less Ergänzungen

**Comment by AWqxKAWERbXo** [comment]
Eigene Feldtypen? Klar, warum nicht! :)
