### ISSUE TITLE
Bestimmte Felder nur für Admins ermöglichen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/yrewrite_domain_settings#21]

**Comment by AWqxKAWERbXo** [comment]
Ups, Mausrutscher.

Es gibt hier drei Ansätze, beide sind nicht offiziell in YForm verbaut.

1. Backend-Rollen je Feld zuweisen können. (Nicht vorhanden)
2. Per EP ausblenden (aber wo definieren?)
3. Tabelle ein 2. Mal in YForm definieren mit den gewünschten Feldern (schon gemacht, aber Felddefintionsn sind dann ggf. nicht synchron)
