### ISSUE TITLE
Versionsbedingung zu yform anpassen

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/yrewrite_domain_settings#22]
Versionsbedingung für yform 4 anpassen.

**Comment by AWqxKAWERbXo** [comment]
In der Zeit hättest du doch auch auf github.com die package.yml kurz bearbeiten können.

https://github.com/FriendsOfREDAXO/yrewrite_domain_settings/edit/master/package.yml

**Comment by marcohanke** [comment]
In der Zeit in der du das alles kommentierst und Daumen verteilst hättest du das doch auch machen können, du hattest die Daten ja sogar schon offen.
Wenn wir einfach überall ungetestet die package.yml anpassen können wir die Abhängigkeiten ja gleich komplett löschen. Ich ging davon aus, dass man das erstmal komplett durchtesten sollte.
