### ISSUE TITLE
Zusätzliche Methoden

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/yrewrite_domain_settings#4]
z.B. das Erhalten eines passenden YRewrite-Domain-Objekts

**Comment by skerbis** [comment]
Was meinst du?

**Comment by AWqxKAWERbXo** [comment]
ich werde es in einem passenden PR vorbereiten und demonstrieren, wie ich das meine...

**Comment by skerbis** [comment]
Bitte keine Methoden von yrewrite duplizieren😉

**Comment by AWqxKAWERbXo** [comment]
nope...
