### ISSUE TITLE
Assets branch anlegen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/yrewrite_domain_settings#6]

**Comment by crydotsnake** [comment]
Würde diese Aufgabe übernehmen!. Einfach einen Leeren Branch anlegen, und direkt pushen?. Oder Branch anlegen, leeren, und dann pushen?.

**Comment by novinet-dsteffen** [comment]
welche assets?

**Comment by skerbis** [comment]
Ein Branch für die Readme assets.

**Comment by skerbis** [comment]
@crydotsnake wie hier beschrieben: https://friendsofredaxo.github.io/info

**Comment by crydotsnake** [comment]
Wird gemacht! :)

**Comment by crydotsnake** [comment]
Kann denn Branch nicht pushen:

```
git push --set-upstream origin assets
error: src refspec assets does not match any
error: failed to push some refs to 'git@github.com:crydotsnake/yrewrite_domain_settings.git'
```

**Comment by crydotsnake** [comment]
Hat geklappt. Ich würde diese Info hier noch Hinzugefügen bei der Erklärung, wie man einen leeren assets branch erstellt: `git commit --allow-empty -m "commit"`

**Comment by skerbis** [comment]
ist aber noch nicht sichtbar

**Comment by crydotsnake** [comment]
Ne, moment.. Hab doch was falsch gemacht. Hätte es nicht Forken dürfen, sondern direkt denn Branch erstellen sollen. Weil Jetzt kann ich Ja kein PR erstellen.

**Comment by crydotsnake** [comment]
@skerbis Branch ist jetzt verfügbar, @skerbis Soll noch eine Beschreibung rein, oder passt das so?.

**Comment by crydotsnake** [comment]
Das bei Mir Jetzt `Compare & Pull Request` steht, ist Ja glaub normal.

**Comment by skerbis** [comment]
ja alles gut , danke
